return Def.ActorFrame{
	Def.BitmapText{
	Font="_Medium",
	Text=THEME:GetString("ScreenEvaluation","Barely!"),
	OnCommand=function(self)
		self:zoom(0.6):strokecolor(Color.Black):y(-12):diffusealpha(0)
		:addy(-20):sleep(3.25):decelerate(0.2):diffusealpha(1):addy(20)
	end;
	},
	Def.BitmapText{
	Text="&MENUDOWN;";
	Font="_Medium";
	OnCommand=function(self)
		self:zoom(0.6):strokecolor(Color.Black):y(0):diffusealpha(0)
		:bob():effectmagnitude(0,5,0)
		:addy(-20):sleep(3.25):decelerate(0.2):diffusealpha(1):addy(30)
	end;
	},
}